apiVersion: catalog.cattle.io/v1
kind: UIPlugin
metadata:
  name: {{ include "extension-server.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{ include "extension-server.labels" . | nindent 4 }}
spec:
  plugin:
    name: {{ include "extension-server.fullname" . }}
    version: {{ (semver (default .Chart.AppVersion .Values.plugin.versionOverride)).Original }}
    endpoint: https://raw.githubusercontent.com/rancher/capi-ui-extension/gh-pages/extensions/capi/0.1.0
    noCache: {{ .Values.plugin.noCache }}
